"""empty message

Revision ID: 26205ef964cd
Revises: 2650235ff2fa
Create Date: 2023-03-26 16:07:08.298504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26205ef964cd'
down_revision = '2650235ff2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorten_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actualUrl', sa.String(), nullable=True),
    sa.Column('shortenUrl', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('urls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original', sa.VARCHAR(), nullable=True),
    sa.Column('short', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shorten_url')
    # ### end Alembic commands ###
